FROM python:3.8

WORKDIR /code

# copy the dependencies file to the working directory
COPY requirements.txt .

# install dependencies
RUN pip install -r requirements.txt

# copy the content of the local src directory to the working directory
COPY master.py sync_tools.py ./

EXPOSE 9000

ENTRYPOINT [ "python" ]
CMD [ "master.py" ]