FROM python:3.8

WORKDIR /code

#test script if a given TCP host/port are available
#RUN wget https://raw.githubusercontent.com/vishnubob/wait-for-it/54d1f0bfeb6557adf8a3204455389d0901652242/wait-for-it.sh
#RUN chmod 755 wait-for-it.sh

# copy the dependencies file to the working directory
COPY requirements.txt .

# install dependencies
RUN pip install -r requirements.txt

# copy the content of the local src directory to the working directory
COPY secondary.py ./


EXPOSE 9001

ENTRYPOINT [ "python" ]
CMD [ "secondary.py" ]
